df <- read.table('household_power_consumption.txt', header=T, sep=';', na.strings='?', colClasses=c('character','character', 'numeric', 'numeric','numeric','numeric','numeric'))
dd <- subset(df, Date=='1/2/2007' |  Date=='2/2/2007' )
dd$DateTime <- strptime( paste(dd$Date, dd$Time), "%d/%m/%Y %H:%M:%S" )

png(filename='plot4.png')
par(mfrow=c(2,2))
with(dd, {
  plot(DateTime, Global_active_power, type="l", xlab="", ylab="Global Active Power")
  plot(DateTime, Voltage, type="l", xlab="datetime", ylab="Voltage")    
  plot(DateTime, Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
  lines(DateTime, Sub_metering_2, col="red")
  lines(DateTime, Sub_metering_3, col="blue")
  legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col=c("black","red","blue"))
  plot(DateTime, Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
})
dev.off()
