df <- read.table('household_power_consumption.txt', header=T, sep=';', na.strings='?', colClasses=c('character','character', 'numeric', 'numeric','numeric','numeric','numeric'))
dd <- subset(df, Date=='1/2/2007' |  Date=='2/2/2007' )
dd$DateTime <- strptime( paste(dd$Date, dd$Time), "%d/%m/%Y %H:%M:%S" )

png(filename='plot3.png')
plot(dd$DateTime, dd$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(dd$DateTime, dd$Sub_metering_2, col="red")
lines(dd$DateTime, dd$Sub_metering_3, col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col=c("black","red","blue"))
dev.off()
